import { Component } from '@angular/core';
import { Title, Meta } from '@angular/platform-browser';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent {
  constructor(
    private title:Title,
    private meta:Meta
  ){}

  ngOnInit(){
    this.title.setTitle('Key Craze, Wholesale Key Blanks and Accessories');
                  this.meta.addTags([ 
                    { name: 'description', content: 'Betty Boop Key Blanks Wholesale Keys , Color Keys Key Blanks , Regular Keys Car Key Blanks Color Key Blanks Main NFL Keys, Team Keys, Lanyards Universal Gun Key Baseball, Key Craze, MLB Keys Basket Ball, Key Craze, NBA Keys Hockey Keys, Key Craze, NHL Keys Nascar Key Blanks Sports Team Keys Main Pop A Lock Guitar Key Blanks, Guitar Keys, ILCO Transponder Keys JMA Key Shells I Love Lucy Key Blanks, Lucille President Obama House Keys Closeout Keys Keys Wholesale , ALL PRODUCTS Titanium Color Keys The Three Stooges Key Blanks Transponder Chips Diva Keys, Rhinestone Keys, Key Marilyn Monroe House Keys, Super Butterfly House Key Blanks - Key LED Key Light Keys Ribbon Key Blanks Custom Key Blanks HY-KO CHIP KEYS Winning Key Promotion Hello Kitty Key Blanks 3D Gun Drill Saw Keys Led Key Blanks Garfield Key Blanks JURASSIC PARK KEYS Pirates of the Caribbean Key Bla Lock Pins Hello Kitty Key Chains Garfield Key Chains Disney Key Blanks College Keys and Lanyards Sporty Key Blanks Racks TK Transponder Key Royal Keys, King and Queen Key B Disney Car House Key Blanks Disney Lanyards JMA Transponder Car Keys EMERGENCY KEY BLADES Key Accessories Promotion Key Blanks ACHILLES INK Motorcycle Keys BIANCHI POD KEYS (KEY SHELLS) ILCO Transponder GTH Head Blades College Team Items vats keys Color Car Keys JMA Clonable Keys Star Wars Key Blanks Artisan Collection Keys Pampered Girls Key Blanks Titanium Car Keys The Real Superhero Keys 3D Key Blanks Main Disney Key Blanks Main KEYLESS REMOTES Celebrity Key Blanks Main Key Chains Main Racks Main Car Keys Main Order Forms Main Videos Main Mailbox Keys Padlock Keys Tool Box Keys Bulk Key Blanks Remote Shells Remote Key Shells Team Bottle Openers Main NFL Team Bottle Opener MLB Team Bottle Opener College Team Bottle Opener ILCO GTS SHELLS Paws and Claws Key Blanks LARGE HEAD COLLEGE KEYS Trendy House Keys BIANCHI TRANSPONDER KEYS BIANCHI HEAD AND BLADES BIANCHI CLONABLE FOBS MACHINE PARTS Displays Custom Painted Keys Engraved Logo Key BATTERIES Happy Keys Unlocking Remote Services STRATTEC KEYS Locksmith T-Shirts Great Outdoors / Deep Woods Kelloggs Keys NFL CARABINER LANYARDS Silver Technology Key Shape Keys SUPERMAN BATMAN KEYS LOONEY TUNES, SPONGEBOB, PANTHER NFL Team Items NBA Team Items MLB Team Items NHL Team Items Key Cutting Machines KOOL KEYS Promotional Lanyards Monthly Specials ILCO Flip Key Housings / Blades BIANCA KEYS Regular Keys Main Rhinestone Keychain Church Key Blanks Real Estate Key Blanks ILCO LOOK-ALIKE REMOTES Wonder Keys Equipment Keys LISHI TOOLS Emboss Keys REFERENCES ecommerce, open source, shop, online shopping, store ' }, 
                    { name: 'keywords', content: 'Key Craze :  - Betty Boop Key Blanks Wholesale Keys , Color Keys Key Blanks , Regular Keys Car Key Blanks Color Key Blanks Main NFL Keys, Team Keys, Lanyards Universal Gun Key Baseball, Key Craze, MLB Keys Basket Ball, Key Craze, NBA Keys Hockey Keys, Key Craze, NHL Keys Nascar Key Blanks Sports Team Keys Main Pop A Lock Guitar Key Blanks, Guitar Keys, ILCO Transponder Keys JMA Key Shells I Love Lucy Key Blanks, Lucille President Obama House Keys Closeout Keys Keys Wholesale , ALL PRODUCTS Titanium Color Keys The Three Stooges Key Blanks Transponder Chips Diva Keys, Rhinestone Keys, Key Marilyn Monroe House Keys, Super Butterfly House Key Blanks - Key LED Key Light Keys Ribbon Key Blanks Custom Key Blanks HY-KO CHIP KEYS Winning Key Promotion Hello Kitty Key Blanks 3D Gun Drill Saw Keys Led Key Blanks Garfield Key Blanks JURASSIC PARK KEYS Pirates of the Caribbean Key Bla Lock Pins Hello Kitty Key Chains Garfield Key Chains Disney Key Blanks College Keys and Lanyards Sporty Key Blanks Racks TK Transponder Key Royal Keys, King and Queen Key B Disney Car House Key Blanks Disney Lanyards JMA Transponder Car Keys EMERGENCY KEY BLADES Key Accessories Promotion Key Blanks ACHILLES INK Motorcycle Keys BIANCHI POD KEYS (KEY SHELLS) ILCO Transponder GTH Head Blades College Team Items vats keys Color Car Keys JMA Clonable Keys Star Wars Key Blanks Artisan Collection Keys Pampered Girls Key Blanks Titanium Car Keys The Real Superhero Keys 3D Key Blanks Main Disney Key Blanks Main KEYLESS REMOTES Celebrity Key Blanks Main Key Chains Main Racks Main Car Keys Main Order Forms Main Videos Main Mailbox Keys Padlock Keys Tool Box Keys Bulk Key Blanks Remote Shells Remote Key Shells Team Bottle Openers Main NFL Team Bottle Opener MLB Team Bottle Opener College Team Bottle Opener ILCO GTS SHELLS Paws and Claws Key Blanks LARGE HEAD COLLEGE KEYS Trendy House Keys BIANCHI TRANSPONDER KEYS BIANCHI HEAD AND BLADES BIANCHI CLONABLE FOBS MACHINE PARTS Displays Custom Painted Keys Engraved Logo Key BATTERIES Happy Keys Unlocking Remote Services STRATTEC KEYS Locksmith T-Shirts Great Outdoors / Deep Woods Kelloggs Keys NFL CARABINER LANYARDS Silver Technology Key Shape Keys SUPERMAN BATMAN KEYS LOONEY TUNES, SPONGEBOB, PANTHER NFL Team Items NBA Team Items MLB Team Items NHL Team Items Key Cutting Machines KOOL KEYS Promotional Lanyards Monthly Specials ILCO Flip Key Housings / Blades BIANCA KEYS Regular Keys Main Rhinestone Keychain Church Key Blanks Real Estate Key Blanks ILCO LOOK-ALIKE REMOTES Wonder Keys Equipment Keys LISHI TOOLS Emboss Keys REFERENCES ecommerce, open source, shop, online shopping, store' } 
                ]);
  }
}
